### PR TITLE
Added more thumbnails

### PR DESCRIPTION
**Pull request by kien-ngo**
List of new thumbnails:
- Dego Finance (https://coinmarketcap.com/currencies/dego-finance/)
- Compound Finance (https://coinmarketcap.com/exchanges/compound/)
- mUSD (https://coinmarketcap.com/currencies/mstable-usd/)
-

### CODE REVIEW

**Comment by kien-ngo** [comment]
Updated some of the latest DEFI project (Late Sep - Oct, 2020)

**Comment by kien-ngo** [comment]
I fixed the typo in the name [compound.png] should be [comp.png]

**Comment by shortcircuit3** [comment]
Looks good! Thanks!

Are you using the api?

**Comment by kien-ngo** [comment]
I'm hosting the icons on my own vercel api page (and use the link in my own project). I'll keep updating the icons (mostly the hot DeFi ones) and later on might create a fancy index page for this project.

**Pull request merged**
